name: Test Api
run-name: Running the test to verify the api is working as expected

on: 
    workflow_run:
        workflows: [Build & Publish Docker Image]
        types:
            - completed

env:
    IMAGE_NAME: ${{secrets.DOCKERHUB_USERNAME}}/${{ github.event.repository.name }}

jobs:
    test-api:
        runs-on: ubuntu-latest
        container: ubuntu:20.04
        services:
            app:
                image: cla0207/node-js-app:latest
                # ports:
                #     - 3001:3000
                env:
                    MONGO_HOSTNAME: mongo
            mongo:
                image: mongo
                # ports:
                #     - 27017:27017
        steps:
            - name: Get Information about services
              run: echo "${{toJson(job.services)}}"
            - name: Install curl
              run: |
                  apt update -y
                  apt install curl -y
            - name: Get Users
              run: curl http://app:3000/api/user


